### ISSUE TITLE
Comentarios practucas y tarea sesion 3

### ISSUE THREAD

**Issue by ferdinandbracho** [sofysha91/KodemiaJS#1]
Hola, estuve revisando tu codigo, super cool, veo que tienes todo super aca en tu repo, solo comentar lo que seguro ya sabes,  no es buena practica usar var para declarar variable, estos por las razones que vimos en clase y que podemos repasar si asi quieres, entonces simepre usemos let cuando son datos que vamos a mutar o que pueden mutar y no var... Tambien y al igual que otros comparneros animarte a usar template litareals para en lughar de hacer concatenacion de string tradicional. Por ejenmplo: console.log(`The second number is the largest: "${numberTwo}"`)

**Comment by sofysha91** [comment]
Gracias por el feedback Ferdinand, he corregido las declaraciones con var y he ido actualizado los console a literals tal como recomendaste.
